POST http://localhost:3001/api/blogs
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNhbmNoZXpAZ21haWwuY29tIiwiaWQiOjMsImlhdCI6MTY4Mzg2NzczM30.fhw2yNoapUxBZCWSy7LZ0lErk9GMq28OXKT-i7BeoVg

{
  "author": "morty",
  "title": "the mort 2",
  "url": "http://mortysmith.com"
}